defmodule QuizProject.Repo.Migrations.AddChapterUsageTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chapters) do
      add :usage_input_tokens, :bigint
      add :usage_output_tokens, :bigint
      add :curated_model, :text
    end
  end

  def down do
    alter table(:chapters) do
      remove :curated_model
      remove :usage_output_tokens
      remove :usage_input_tokens
    end
  end
end
