defmodule QuizProject.Repo.Migrations.AddChapterEstimatedTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chapters) do
      add :estimated_tokens, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:chapters) do
      remove :estimated_tokens
    end
  end
end
