defmodule QuizProject.Repo.Migrations.Fase2Quizzes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:quizzes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :public_slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :owner_id,
          references(:users,
            column: :id,
            name: "quizzes_owner_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:quizzes, [:public_slug], name: "quizzes_unique_public_slug_index")

    create table(:quiz_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_number, :bigint, null: false, default: 1
      add :name, :text, default: ""
      add :description, :text, default: ""
      add :total_points, :decimal, null: false, default: "100"
      add :unequal_weights, :boolean, null: false, default: false
      add :question_order_mode, :text, null: false, default: "fixed"
      add :status, :text, null: false, default: "draft"
      add :published_at, :utc_datetime_usec
      add :changelog, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :quiz_id,
          references(:quizzes,
            column: :id,
            name: "quiz_versions_quiz_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:quiz_versions, [:quiz_id, :version_number],
             name: "quiz_versions_unique_version_per_quiz_index"
           )

    create table(:questions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :identity_key, :uuid, null: false
      add :position, :bigint, null: false, default: 0
      add :statement, :text, null: false, default: ""
      add :type, :text, null: false, default: "single"
      add :allow_partial_credit, :boolean, null: false, default: false
      add :true_false_answer, :boolean
      add :reference_answer, :text
      add :editor_note, :text
      add :weight, :decimal
      add :annulled, :boolean, null: false, default: false
      add :annulled_reason, :text
      add :annulled_at, :utc_datetime_usec
      add :ai_tags, {:array, :text}, null: false, default: []
      add :compatibility_hash, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :quiz_version_id,
          references(:quiz_versions,
            column: :id,
            name: "questions_quiz_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create table(:options, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :identity_key, :uuid, null: false
      add :position, :bigint, null: false, default: 0
      add :text, :text, null: false, default: ""
      add :correct, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id,
          references(:questions,
            column: :id,
            name: "options_question_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:options, "options_question_id_fkey")

    drop table(:options)

    drop constraint(:questions, "questions_quiz_version_id_fkey")

    drop table(:questions)

    drop constraint(:quiz_versions, "quiz_versions_quiz_id_fkey")

    drop_if_exists unique_index(:quiz_versions, [:quiz_id, :version_number],
                     name: "quiz_versions_unique_version_per_quiz_index"
                   )

    drop table(:quiz_versions)

    drop constraint(:quizzes, "quizzes_owner_id_fkey")

    drop_if_exists unique_index(:quizzes, [:public_slug],
                     name: "quizzes_unique_public_slug_index"
                   )

    drop table(:quizzes)
  end
end
