defmodule QuizProject.Repo.Migrations.AddActivitiesAndItemLinks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:priority_item_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :link_type, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_item_links_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :related_item_id,
          references(:priority_items,
            column: :id,
            name: "priority_item_links_related_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:priority_item_links, [:item_id, :related_item_id, :link_type],
             name: "priority_item_links_item_link_index"
           )

    create table(:priority_activities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "priority_activities_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_activities_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :title, :text, null: false, default: ""
      add :notes, :text, default: ""
      add :status, :text, null: false, default: "pendente"
      add :flow, :text, null: false, default: "todo"
      add :logical_date, :date, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:priority_activities, "priority_activities_user_id_fkey")

    drop constraint(:priority_activities, "priority_activities_item_id_fkey")

    drop table(:priority_activities)

    drop constraint(:priority_item_links, "priority_item_links_item_id_fkey")

    drop constraint(:priority_item_links, "priority_item_links_related_item_id_fkey")

    drop_if_exists unique_index(:priority_item_links, [:item_id, :related_item_id, :link_type],
                     name: "priority_item_links_item_link_index"
                   )

    drop table(:priority_item_links)
  end
end
