defmodule QuizProject.Repo.Migrations.AddPriorities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:priority_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "priority_tags_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false, default: ""

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:priority_tags, [:user_id, :name], name: "priority_tags_user_name_index")

    create table(:priority_items, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "priority_items_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :category_id, :uuid, null: false
      add :item_type, :text, null: false
      add :title, :text, null: false, default: ""
      add :notes, :text, default: ""
      add :position, :bigint, null: false, default: 0
      add :archived_at, :utc_datetime_usec
      add :tier, :text
      add :study_material_id, :uuid
      add :quiz_id, :uuid
      add :course_total_steps, :bigint
      add :course_completed_steps, :bigint, default: 0
      add :habit_current_streak, :bigint, default: 0
      add :habit_last_checked_on, :date
      add :manual_percent, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:priority_item_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false, default: ""
      add :done, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_item_tasks_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create table(:priority_item_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_item_tags_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :tag_id,
          references(:priority_tags,
            column: :id,
            name: "priority_item_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:priority_item_tags, [:item_id, :tag_id],
             name: "priority_item_tags_item_tag_index"
           )

    create table(:priority_item_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_item_categories_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :category_id, :uuid, null: false
    end

    create unique_index(:priority_item_categories, [:item_id, :category_id],
             name: "priority_item_categories_item_category_index"
           )

    create table(:priority_field_values, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :value_text, :text
      add :value_number, :float

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_field_values_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :field_definition_id, :uuid, null: false
    end

    create unique_index(:priority_field_values, [:item_id, :field_definition_id],
             name: "priority_field_values_item_field_index"
           )

    create table(:priority_field_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:priority_field_values) do
      modify :field_definition_id,
             references(:priority_field_definitions,
               column: :id,
               name: "priority_field_values_field_definition_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:priority_field_definitions) do
      add :user_id,
          references(:users,
            column: :id,
            name: "priority_field_definitions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false, default: ""
      add :field_type, :text, null: false
      add :select_options, {:array, :text}, null: false, default: []
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:priority_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:priority_items) do
      modify :category_id,
             references(:priority_categories,
               column: :id,
               name: "priority_items_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )

      modify :study_material_id,
             references(:study_materials,
               column: :id,
               name: "priority_items_study_material_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )

      modify :quiz_id,
             references(:quizzes,
               column: :id,
               name: "priority_items_quiz_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    alter table(:priority_item_categories) do
      modify :category_id,
             references(:priority_categories,
               column: :id,
               name: "priority_item_categories_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:priority_categories) do
      add :user_id,
          references(:users,
            column: :id,
            name: "priority_categories_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :name, :text, null: false, default: ""
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:priority_categories, "priority_categories_user_id_fkey")

    alter table(:priority_categories) do
      remove :updated_at
      remove :inserted_at
      remove :position
      remove :name
      remove :user_id
    end

    drop constraint(:priority_item_categories, "priority_item_categories_category_id_fkey")

    alter table(:priority_item_categories) do
      modify :category_id, :uuid
    end

    drop constraint(:priority_items, "priority_items_category_id_fkey")

    drop constraint(:priority_items, "priority_items_study_material_id_fkey")

    drop constraint(:priority_items, "priority_items_quiz_id_fkey")

    alter table(:priority_items) do
      modify :quiz_id, :uuid
      modify :study_material_id, :uuid
      modify :category_id, :uuid
    end

    drop table(:priority_categories)

    drop constraint(:priority_field_definitions, "priority_field_definitions_user_id_fkey")

    alter table(:priority_field_definitions) do
      remove :updated_at
      remove :inserted_at
      remove :position
      remove :select_options
      remove :field_type
      remove :name
      remove :user_id
    end

    drop constraint(:priority_field_values, "priority_field_values_field_definition_id_fkey")

    alter table(:priority_field_values) do
      modify :field_definition_id, :uuid
    end

    drop table(:priority_field_definitions)

    drop constraint(:priority_field_values, "priority_field_values_item_id_fkey")

    drop_if_exists unique_index(:priority_field_values, [:item_id, :field_definition_id],
                     name: "priority_field_values_item_field_index"
                   )

    drop table(:priority_field_values)

    drop constraint(:priority_item_categories, "priority_item_categories_item_id_fkey")

    drop_if_exists unique_index(:priority_item_categories, [:item_id, :category_id],
                     name: "priority_item_categories_item_category_index"
                   )

    drop table(:priority_item_categories)

    drop constraint(:priority_item_tags, "priority_item_tags_item_id_fkey")

    drop constraint(:priority_item_tags, "priority_item_tags_tag_id_fkey")

    drop_if_exists unique_index(:priority_item_tags, [:item_id, :tag_id],
                     name: "priority_item_tags_item_tag_index"
                   )

    drop table(:priority_item_tags)

    drop constraint(:priority_item_tasks, "priority_item_tasks_item_id_fkey")

    drop table(:priority_item_tasks)

    drop constraint(:priority_items, "priority_items_user_id_fkey")

    drop table(:priority_items)

    drop constraint(:priority_tags, "priority_tags_user_id_fkey")

    drop_if_exists unique_index(:priority_tags, [:user_id, :name],
                     name: "priority_tags_user_name_index"
                   )

    drop table(:priority_tags)
  end
end
