defmodule QuizProject.Repo.Migrations.AddChapterAiCuration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:chapters) do
      add :curation_status, :text, null: false, default: "none"

      add :curated_material_id,
          references(:study_materials,
            column: :id,
            name: "chapters_curated_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end

    create index(:chapters, [:curated_material_id])
  end

  def down do
    drop_if_exists index(:chapters, [:curated_material_id])

    drop constraint(:chapters, "chapters_curated_material_id_fkey")

    alter table(:chapters) do
      remove :curated_material_id
      remove :curation_status
    end
  end
end
