defmodule QuizProject.Repo.Migrations.RenameActivityLogsToHistoryLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # `priority_activity_logs` (criada em 20260831233128) generalizou pra
    # cobrir categoria/prioridade também, não só atividade — o codegen do
    # Ash não faz rename de tabela sozinho, então recriamos do zero como
    # `priority_history_logs`. Tabela nova há poucas horas, sem dado real
    # em produção ainda, então dropar em vez de migrar linha a linha é
    # seguro aqui.
    drop constraint(:priority_activity_logs, "priority_activity_logs_user_id_fkey")
    drop constraint(:priority_activity_logs, "priority_activity_logs_activity_id_fkey")
    drop table(:priority_activity_logs)

    create table(:priority_history_logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "priority_history_logs_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :activity_id,
          references(:priority_activities,
            column: :id,
            name: "priority_history_logs_activity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :category_id,
          references(:priority_categories,
            column: :id,
            name: "priority_history_logs_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_history_logs_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :message, :text, null: false
      add :logical_date, :date, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:priority_history_logs, "priority_history_logs_user_id_fkey")

    drop constraint(:priority_history_logs, "priority_history_logs_activity_id_fkey")

    drop constraint(:priority_history_logs, "priority_history_logs_category_id_fkey")

    drop constraint(:priority_history_logs, "priority_history_logs_item_id_fkey")

    drop table(:priority_history_logs)
  end
end
