defmodule QuizProject.Repo.Migrations.AddActivitySnoozedUntil do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_activities) do
      add :snoozed_until, :date
    end
  end

  def down do
    alter table(:priority_activities) do
      remove :snoozed_until
    end
  end
end
