defmodule QuizProject.Repo.Migrations.AddManualProgressMode do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_items) do
      add :manual_progress_mode, :text, null: false, default: "percent"
      add :manual_total_steps, :bigint
      add :manual_completed_steps, :bigint, default: 0
    end
  end

  def down do
    alter table(:priority_items) do
      remove :manual_completed_steps
      remove :manual_total_steps
      remove :manual_progress_mode
    end
  end
end
