defmodule QuizProject.Repo.Migrations.AddPointDefaults do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:priority_point_defaults, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "priority_point_defaults_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :activity_points, :bigint, null: false, default: 0
      add :activity_task_points, :bigint, null: false, default: 0
      add :item_points, :bigint, null: false, default: 0
      add :habit_points, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:priority_point_defaults, [:user_id],
             name: "priority_point_defaults_unique_user_index"
           )

    alter table(:priority_items) do
      add :default_activity_store_points, :bigint
    end
  end

  def down do
    alter table(:priority_items) do
      remove :default_activity_store_points
    end

    drop constraint(:priority_point_defaults, "priority_point_defaults_user_id_fkey")

    drop_if_exists unique_index(:priority_point_defaults, [:user_id],
                     name: "priority_point_defaults_unique_user_index"
                   )

    drop table(:priority_point_defaults)
  end
end
