defmodule QuizProject.Repo.Migrations.AddApiTokens do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_tokens, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false, default: "Integração API"
      add :token_hash, :text, null: false

      add :scopes, {:array, :text}, null: false

      add :last_used_at, :utc_datetime_usec
      add :expires_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "api_tokens_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:api_tokens, [:token_hash], name: "api_tokens_unique_token_hash_index")
  end

  def down do
    drop constraint(:api_tokens, "api_tokens_user_id_fkey")

    drop_if_exists unique_index(:api_tokens, [:token_hash],
                     name: "api_tokens_unique_token_hash_index"
                   )

    drop table(:api_tokens)
  end
end
