defmodule QuizProject.Repo.Migrations.AddNodeBlockChapterId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists index(:node_blocks, [:material_id, :node_id, :block_id])

    drop_if_exists index(:node_blocks, [:material_id, :node_id])

    alter table(:node_blocks) do
      add :chapter_id,
          references(:chapters,
            column: :id,
            name: "node_blocks_chapter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          )
    end

    create index(:node_blocks, [:chapter_id, :node_id, :block_id], unique: true)

    create index(:node_blocks, [:chapter_id, :node_id])
  end

  def down do
    drop constraint(:node_blocks, "node_blocks_chapter_id_fkey")

    drop_if_exists index(:node_blocks, [:chapter_id, :node_id])

    drop_if_exists index(:node_blocks, [:chapter_id, :node_id, :block_id])

    alter table(:node_blocks) do
      remove :chapter_id
    end

    create index(:node_blocks, [:material_id, :node_id])

    create index(:node_blocks, [:material_id, :node_id, :block_id], unique: true)
  end
end
