defmodule QuizProject.Repo.Migrations.AddActivityTasks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:priority_activity_tasks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false, default: ""
      add :done, :boolean, null: false, default: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :activity_id,
          references(:priority_activities,
            column: :id,
            name: "priority_activity_tasks_activity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end
  end

  def down do
    drop constraint(:priority_activity_tasks, "priority_activity_tasks_activity_id_fkey")

    drop table(:priority_activity_tasks)
  end
end
