defmodule QuizProject.Repo.Migrations.AddActivityMaxDeadline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_activities) do
      add :max_deadline, :date
    end
  end

  def down do
    alter table(:priority_activities) do
      remove :max_deadline
    end
  end
end
