defmodule QuizProject.Repo.Migrations.AddStorePoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_items) do
      add :store_points, :bigint, null: false, default: 0
    end

    alter table(:priority_habits) do
      add :store_points, :bigint, null: false, default: 0
    end

    alter table(:priority_activity_tasks) do
      add :store_points, :bigint, null: false, default: 0
    end

    alter table(:priority_activities) do
      add :store_points, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:priority_activities) do
      remove :store_points
    end

    alter table(:priority_activity_tasks) do
      remove :store_points
    end

    alter table(:priority_habits) do
      remove :store_points
    end

    alter table(:priority_items) do
      remove :store_points
    end
  end
end
