defmodule QuizProject.Repo.Migrations.AddEpubReader do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:study_materials) do
      add :format, :text, null: false, default: "text"
      add :author, :text
      add :reader_css, :text
      add :ingest_error, :text
    end

    create table(:reading_preferences, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :font, :text, null: false, default: "serif"
      add :font_size, :bigint, null: false, default: 100
      add :line_height, :bigint, null: false, default: 175
      add :width, :text, null: false, default: "medium"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:reading_preferences, [:user_id],
             name: "reading_preferences_unique_user_index"
           )

    create table(:reading_positions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false

      add :material_id,
          references(:study_materials,
            column: :id,
            name: "reading_positions_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :chapter_id, :uuid, null: false
      add :block_position, :bigint, null: false, default: 1
      add :offset, :float, null: false, default: 0.0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:reading_positions, [:user_id, :material_id],
             name: "reading_positions_user_material_index"
           )

    create table(:node_blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :material_id,
          references(:study_materials,
            column: :id,
            name: "node_blocks_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :node_id, :text, null: false
      add :block_id, :uuid, null: false
      add :confidence, :decimal, null: false, default: "1.0"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:node_blocks, [:material_id, :node_id, :block_id], unique: true)

    create index(:node_blocks, [:material_id, :node_id])

    create index(:node_blocks, [:block_id])

    create table(:chapters, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :material_id,
          references(:study_materials,
            column: :id,
            name: "chapters_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :source_id, :text, null: false, default: ""
      add :href, :text, null: false, default: ""
      add :title, :text, null: false, default: ""
      add :position, :bigint, null: false
      add :level, :bigint, null: false, default: 1
      add :kind, :text, null: false, default: "body"
      add :block_count, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:chapters, [:material_id, :position], unique: true)

    create index(:chapters, [:material_id])

    create table(:blocks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:node_blocks) do
      modify :block_id,
             references(:blocks,
               column: :id,
               name: "node_blocks_block_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all,
               on_update: :update_all
             )
    end

    alter table(:blocks) do
      add :material_id,
          references(:study_materials,
            column: :id,
            name: "blocks_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :chapter_id,
          references(:chapters,
            column: :id,
            name: "blocks_chapter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :source_id, :text
      add :position, :bigint, null: false
      add :type, :text, null: false, default: "paragraph"
      add :lang, :text
      add :caption, :text
      add :content, :text, null: false, default: ""
      add :annotations, {:array, :text}, null: false, default: []
    end

    create index(:blocks, ["to_tsvector('simple', content)"],
             name: "blocks_content_search_index",
             using: "gin"
           )

    create index(:blocks, [:material_id, :position], unique: true)

    create index(:blocks, [:chapter_id, :position])
  end

  def down do
    drop constraint(:blocks, "blocks_material_id_fkey")

    drop constraint(:blocks, "blocks_chapter_id_fkey")

    drop_if_exists index(:blocks, [:chapter_id, :position])

    drop_if_exists index(:blocks, [:material_id, :position])

    drop_if_exists index(:blocks, ["to_tsvector('simple', content)"],
                     name: "blocks_content_search_index"
                   )

    alter table(:blocks) do
      remove :annotations
      remove :content
      remove :caption
      remove :lang
      remove :type
      remove :position
      remove :source_id
      remove :chapter_id
      remove :material_id
    end

    drop constraint(:node_blocks, "node_blocks_block_id_fkey")

    alter table(:node_blocks) do
      modify :block_id, :uuid
    end

    drop table(:blocks)

    drop_if_exists index(:chapters, [:material_id])

    drop constraint(:chapters, "chapters_material_id_fkey")

    drop_if_exists index(:chapters, [:material_id, :position])

    drop table(:chapters)

    drop constraint(:node_blocks, "node_blocks_material_id_fkey")

    drop_if_exists index(:node_blocks, [:block_id])

    drop_if_exists index(:node_blocks, [:material_id, :node_id])

    drop_if_exists index(:node_blocks, [:material_id, :node_id, :block_id])

    drop table(:node_blocks)

    drop constraint(:reading_positions, "reading_positions_material_id_fkey")

    drop_if_exists unique_index(:reading_positions, [:user_id, :material_id],
                     name: "reading_positions_user_material_index"
                   )

    drop table(:reading_positions)

    drop_if_exists unique_index(:reading_preferences, [:user_id],
                     name: "reading_preferences_unique_user_index"
                   )

    drop table(:reading_preferences)

    alter table(:study_materials) do
      remove :ingest_error
      remove :reader_css
      remove :author
      remove :format
    end
  end
end
