defmodule QuizProject.Repo.Migrations.AddHabitOverridesAndDateBounds do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_habits) do
      add :starts_on, :date
      add :ends_on, :date
    end

    create table(:priority_habit_overrides, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :date, :date, null: false
      add :skipped, :boolean, null: false, default: false
      add :title, :text
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :habit_id,
          references(:priority_habits,
            column: :id,
            name: "priority_habit_overrides_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:priority_habit_overrides, [:habit_id, :date],
             name: "priority_habit_overrides_habit_date_index"
           )
  end

  def down do
    drop constraint(:priority_habit_overrides, "priority_habit_overrides_habit_id_fkey")

    drop_if_exists unique_index(:priority_habit_overrides, [:habit_id, :date],
                     name: "priority_habit_overrides_habit_date_index"
                   )

    drop table(:priority_habit_overrides)

    alter table(:priority_habits) do
      remove :ends_on
      remove :starts_on
    end
  end
end
