defmodule QuizProject.Repo.Migrations.AddStudyMaterials do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:study_materials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "study_materials_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :title, :text, null: false, default: ""
      add :raw_content, :text, null: false, default: ""
      add :summary, :text, default: ""
      add :mindmap_tree, :map, null: false, default: %{}
      add :key_concepts, :map, null: false, default: %{}
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:study_materials, "study_materials_user_id_fkey")

    drop table(:study_materials)
  end
end
