defmodule QuizProject.Repo.Migrations.AddHabitAndActivityHabitId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:priority_habits, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "priority_habits_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :category_id,
          references(:priority_categories,
            column: :id,
            name: "priority_habits_category_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )

      add :title, :text, null: false, default: ""
      add :frequency, :text, null: false, default: "daily"
      add :weekdays, {:array, :bigint}, null: false, default: []
      add :month_days, {:array, :bigint}, null: false, default: []
      add :archived_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:priority_activities) do
      add :habit_id,
          references(:priority_habits,
            column: :id,
            name: "priority_activities_habit_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all,
            on_update: :update_all
          )
    end
  end

  def down do
    drop constraint(:priority_activities, "priority_activities_habit_id_fkey")

    alter table(:priority_activities) do
      remove :habit_id
    end

    drop constraint(:priority_habits, "priority_habits_user_id_fkey")

    drop constraint(:priority_habits, "priority_habits_category_id_fkey")

    drop table(:priority_habits)
  end
end
