defmodule QuizProject.Repo.Migrations.AddCourseAccessAndChangeType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_items) do
      add :course_access_link, :text
      add :course_access_login, :text
      add :course_access_password, :text
    end
  end

  def down do
    alter table(:priority_items) do
      remove :course_access_password
      remove :course_access_login
      remove :course_access_link
    end
  end
end
