defmodule QuizProject.Repo.Migrations.AddCategoryDefaultItemPoints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_categories) do
      add :default_item_store_points, :bigint
    end
  end

  def down do
    alter table(:priority_categories) do
      remove :default_item_store_points
    end
  end
end
