defmodule QuizProject.Repo.Migrations.AddHighlights do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:highlights, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false

      add :material_id,
          references(:study_materials,
            column: :id,
            name: "highlights_material_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :chapter_id,
          references(:chapters,
            column: :id,
            name: "highlights_chapter_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :block_id,
          references(:blocks,
            column: :id,
            name: "highlights_block_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :start_offset, :bigint, null: false
      add :end_offset, :bigint, null: false
      add :quote, :text, null: false
      add :note, :text
      add :color, :text, null: false, default: "yellow"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:highlights, [:user_id, :material_id])

    create index(:highlights, [:block_id])
  end

  def down do
    drop constraint(:highlights, "highlights_material_id_fkey")

    drop constraint(:highlights, "highlights_chapter_id_fkey")

    drop constraint(:highlights, "highlights_block_id_fkey")

    drop_if_exists index(:highlights, [:block_id])

    drop_if_exists index(:highlights, [:user_id, :material_id])

    drop table(:highlights)
  end
end
