defmodule QuizProject.Repo.Migrations.UnificaRespostaReferencia do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:questions) do
      remove :reference_answer
    end
  end

  def down do
    alter table(:questions) do
      add :reference_answer, :text
    end
  end
end
