defmodule QuizProject.Repo.Migrations.AddGoogleCalendarSync do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:google_calendar_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :google_account_email, :text, null: false
      add :access_token, :binary, null: false
      add :refresh_token, :binary, null: false
      add :access_token_expires_at, :utc_datetime_usec, null: false
      add :calendar_id, :text, null: false
      add :sync_token, :text
      add :channel_id, :text
      add :channel_token_hash, :text
      add :channel_resource_id, :text
      add :channel_expires_at, :utc_datetime_usec
      add :last_synced_at, :utc_datetime_usec
      add :last_sync_error, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "google_calendar_connections_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:google_calendar_connections, [:channel_id],
             name: "google_calendar_connections_unique_channel_id_index"
           )

    create unique_index(:google_calendar_connections, [:user_id],
             name: "google_calendar_connections_unique_user_index"
           )
  end

  def down do
    drop constraint(:google_calendar_connections, "google_calendar_connections_user_id_fkey")

    drop_if_exists unique_index(:google_calendar_connections, [:user_id],
                     name: "google_calendar_connections_unique_user_index"
                   )

    drop_if_exists unique_index(:google_calendar_connections, [:channel_id],
                     name: "google_calendar_connections_unique_channel_id_index"
                   )

    drop table(:google_calendar_connections)
  end
end
