defmodule QuizProject.Repo.Migrations.Fase4Tentativas do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:attempts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :display_identity, :text, null: false
      add :participant_token, :text
      add :status, :text, null: false, default: "in_progress"
      add :question_order, {:array, :uuid}, null: false, default: []
      add :started_at, :utc_datetime_usec
      add :finished_at, :utc_datetime_usec
      add :score, :decimal
      add :max_score, :decimal
      add :percent, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :quiz_version_id,
          references(:quiz_versions,
            column: :id,
            name: "attempts_quiz_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "attempts_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :nilify_all
          )
    end

    create table(:answers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false, default: "unanswered"
      add :payload, :map
      add :marked_later, :boolean, null: false, default: false
      add :imported_from_previous, :boolean, null: false, default: false
      add :cleared_backup, :map
      add :cleared_at, :utc_datetime_usec
      add :score, :decimal
      add :ai_percent, :bigint
      add :ai_feedback, :text
      add :ai_reference, :text
      add :ai_reference_generated, :boolean, null: false, default: false
      add :graded_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :attempt_id,
          references(:attempts,
            column: :id,
            name: "answers_attempt_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :question_id,
          references(:questions,
            column: :id,
            name: "answers_question_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:answers, [:attempt_id, :question_id],
             name: "answers_unique_question_per_attempt_index"
           )
  end

  def down do
    drop constraint(:answers, "answers_attempt_id_fkey")

    drop constraint(:answers, "answers_question_id_fkey")

    drop_if_exists unique_index(:answers, [:attempt_id, :question_id],
                     name: "answers_unique_question_per_attempt_index"
                   )

    drop table(:answers)

    drop constraint(:attempts, "attempts_quiz_version_id_fkey")

    drop constraint(:attempts, "attempts_user_id_fkey")

    drop table(:attempts)
  end
end
