defmodule QuizProject.Repo.Migrations.AddActivityGoogleEvent do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_activities) do
      add :google_event_id, :text
      add :google_updated_at, :utc_datetime_usec
    end

    create unique_index(:priority_activities, [:google_event_id],
             name: "priority_activities_unique_google_event_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:priority_activities, [:google_event_id],
                     name: "priority_activities_unique_google_event_id_index"
                   )

    alter table(:priority_activities) do
      remove :google_updated_at
      remove :google_event_id
    end
  end
end
