defmodule QuizProject.Repo.Migrations.AddProductLinkFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:store_products) do
      add :link_url, :text
      add :link_text, :text
    end
  end

  def down do
    alter table(:store_products) do
      remove :link_text
      remove :link_url
    end
  end
end
