defmodule QuizProject.Repo.Migrations.DesativarQuiz do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:quizzes) do
      add :active, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:quizzes) do
      remove :active
    end
  end
end
