defmodule QuizProject.Repo.Migrations.AddUniqueTaskPerDay do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`,
  with a dedupe step added by hand before `up/0` creates the unique index —
  duplicatas de atividade comum já existiam em produção (bug de duplo-submit
  sem `phx-disable-with`), e o índice único falharia ao ser criado se elas
  ainda estivessem lá. Mantém sempre a linha mais antiga do grupo
  (`inserted_at` menor, `id` como desempate) — mesmo critério do
  `mix priorities.dedupe_activities`, usado localmente pra inspecionar antes
  do deploy.
  """

  use Ecto.Migration

  def up do
    execute("""
    DELETE FROM priority_activities pa
    USING (
      SELECT id,
             row_number() OVER (
               PARTITION BY user_id, item_id, habit_id, title, logical_date
               ORDER BY inserted_at ASC, id ASC
             ) AS rn
      FROM priority_activities
      WHERE kind = 'tarefa'
    ) ranked
    WHERE pa.id = ranked.id
      AND ranked.rn > 1
    """)

    create unique_index(
             :priority_activities,
             [:user_id, :item_id, :habit_id, :title, :logical_date],
             name: "priority_activities_unique_task_per_day_index",
             nulls_distinct: false,
             where: "(kind = 'tarefa')"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :priority_activities,
                     [:user_id, :item_id, :habit_id, :title, :logical_date],
                     name: "priority_activities_unique_task_per_day_index"
                   )
  end
end
