defmodule QuizProject.Repo.Migrations.AddGeneralItemToCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_items) do
      add :general, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:priority_items) do
      remove :general
    end
  end
end
