defmodule QuizProject.Repo.Migrations.AddHabitConfigAndRemoveItemColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_items) do
      remove :habit_last_checked_on
      remove :habit_current_streak
    end

    create table(:priority_habit_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :frequency, :text, null: false, default: "daily"
      add :weekdays, {:array, :bigint}, null: false, default: []
      add :month_days, {:array, :bigint}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :item_id,
          references(:priority_items,
            column: :id,
            name: "priority_habit_configs_item_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false
    end

    create unique_index(:priority_habit_configs, [:item_id],
             name: "priority_habit_configs_item_id_index"
           )
  end

  def down do
    drop constraint(:priority_habit_configs, "priority_habit_configs_item_id_fkey")

    drop_if_exists unique_index(:priority_habit_configs, [:item_id],
                     name: "priority_habit_configs_item_id_index"
                   )

    drop table(:priority_habit_configs)

    alter table(:priority_items) do
      add :habit_current_streak, :bigint, default: 0
      add :habit_last_checked_on, :date
    end
  end
end
