defmodule QuizProject.Repo.Migrations.AddStoreProducts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:store_redemptions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "store_redemptions_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :product_id, :uuid
      add :price, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:store_products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:store_redemptions) do
      modify :product_id,
             references(:store_products,
               column: :id,
               name: "store_redemptions_product_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all,
               on_update: :update_all
             )
    end

    alter table(:store_products) do
      add :user_id,
          references(:users,
            column: :id,
            name: "store_products_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :name, :text, null: false
      add :description, :text, null: false
      add :price, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:store_product_images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :product_id,
          references(:store_products,
            column: :id,
            name: "store_product_images_product_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all,
            on_update: :update_all
          ),
          null: false

      add :path, :text, null: false
      add :position, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:store_product_images, "store_product_images_product_id_fkey")

    drop table(:store_product_images)

    drop constraint(:store_products, "store_products_user_id_fkey")

    alter table(:store_products) do
      remove :updated_at
      remove :inserted_at
      remove :price
      remove :description
      remove :name
      remove :user_id
    end

    drop constraint(:store_redemptions, "store_redemptions_product_id_fkey")

    alter table(:store_redemptions) do
      modify :product_id, :uuid
    end

    drop table(:store_products)

    drop constraint(:store_redemptions, "store_redemptions_user_id_fkey")

    drop table(:store_redemptions)
  end
end
