defmodule QuizProject.Repo.Migrations.AddActivityKind do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:priority_activities) do
      add :kind, :text, null: false, default: "tarefa"
    end
  end

  def down do
    alter table(:priority_activities) do
      remove :kind
    end
  end
end
